apiVersion: batch/v1
kind: Job
metadata:
  name: upload-file
spec:
  template:
    spec:
      containers:
        - name: uploader
          image: minio/mc
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 10 && \
              mc alias set local http://minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY && \
              mc mb local/{{ .Values.minio.bucketName }} || true && \
              mc cp /data/index.html local/{{ .Values.minio.bucketName }}/
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.credentialsSecret }}
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.credentialsSecret }}
                  key: secretkey
          volumeMounts:
            - name: html
              mountPath: /data
      restartPolicy: OnFailure
      volumes:
        - name: html
          configMap:
            name: html-file
