version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  terraform-deploy:
    desc: 🛠 Deploy infrastructure using Terraform
    dir: terraform
    cmds:
      - echo "🚀 Initializing Terraform..."
      - terraform init
      - echo "✅ Terraform initialized!"
      - echo "📦 Applying Terraform..."
      - terraform apply -auto-approve
      - echo "✅ Terraform apply complete!"

  open-app:
    desc: 🌐 Open s3www NodePort URL in browser
    cmds:
      - |
        echo "🌐 Trying to open the s3www URL..."
        PORT=$(kubectl get svc s3www -o=jsonpath='{.spec.ports[0].nodePort}')
        echo "➡ http://localhost:$PORT"
        if command -v xdg-open > /dev/null; then
          xdg-open http://localhost:$PORT
        elif command -v open > /dev/null; then
          open http://localhost:$PORT
        else
          echo "Please open http://localhost:$PORT manually."
        fi

  status:
    desc: 📋 Show Kubernetes pods and services
    cmds:
      - kubectl get pods
      - kubectl get svc

  destroy:
    desc: 🧹 Tear down infrastructure
    dir: terraform
    cmds:
      - echo "🧨 Destroying all resources..."
      - terraform destroy -auto-approve
      - echo "🧼 All resources destroyed."

  setup:
    desc: 🔧 Full setup pipeline (Terraform + open URL)
    deps: [terraform-deploy, status, open-app]
