---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: default
spec:
  encryptedData:
    accesskey: AgAOEyqad9koWqPRKAb3cHQHzg5H66E2CKFw/XZ1NvfA4hseFL3oCb32ik22TD8jxQ1bZwfY/m1LKfxceqhdJe+e40norQYFPLXAhXTmatxDij6nnsUmITtT6j4jDgcQ0hVQpUkKkTH6bB4X9oedn/swnorGR/jWtkOlDQ1Yki55L2L8XmLLYEBDG5Igap74+5ugv0AC6Iv2/DJUA4ntzasEzkRYF2fHvu2ufFHZfMeiRED0LuSvL8CARRG0xTYlr4KOjVka952/z1RBkUdPp3KS5ZHKmS3WmbnV7zJYJ512go8aSx/NP6JiqEl/K2XKBJJPuG2I6MRH8SIqI24ZscDyMoqDxMUy/0YaFHkxoly5AVAHgcjEJUxrkQh3uqZBarrSCcunlEnRAPup/q8ZF/khKn0SZ3o+k55lyfoj5LfKe84hcbQ7Sx+R5uonNkC0LdU825lWgDm69vOBKJb/kauoBbcCHGRGCvbk8Sk3F/7djYzoQCMEYx83pgoIENSholXVHmMywHnZhjer1o4thjmAis+7wPwXPXYmvgyNxnnfdw9qgKHpPPzJQQ4BbreQNSGqDntLj6BiszwJgi8fRu+mF/n4GIW0zR+iiJuEIMOtHCFMYNFSi8BzB75E7gcvOoIpjaxEkFK9lSqMxnVr/PMmg59sszEA7Zatjq2YKZ1WWqDkOp9yV/2cX1DcfN+v15n4yuqLASdWKC1P
    secretkey: AgAzeSoYCxP+uLicN2KQ54QK+Co73KOswEXRnBJptqMmCb+E6AoB2o0juqODCqddiTq6Hd926J5rW90zyDBfIzWuOcuBFNU2VDmQB0S+OHkG2UCobRplHV2C1nomfmGOwiFS7bEbDohNbDtL8/DFovAZ1pn/DnmiQws9jcwuheD63Fj+gs4IFSkRlkGqrty40u2aeN03OQuI5v3bAU82gznkEg3hkI8bDZD+VKHEWB0xlH3ckPge52blB5bdoucRg54lz5JS3qG9xQgPWI/7XKAjYCNaTzozKAy/4uX9+YOsiCEU8716onRc99AyDcn3KoMs7qLiDeyhMT45eznTvQIgThG/1EgjI/TYC/uJuOoynE1+ZufNH/8TtZD2knXlBNYuNx7ZsAygXJln5WkdyPDEawoRxtKEAFFl3z3ZgqC2haEnaeM19HYOopLcarZ9xVLaVK10yybYXZh/Tdd5uwQ11UTYREqqsHSzWTB94a0TS1t+zOz131QV06JqGEaPuBp42Ojua70kMaMnC/VR2TjWcyRu2ODP6lIOQkNiEq6fvsY+I0RTiUidVAcD3e4jLKpV1ukvLe8vbAmhg9cdEQ+kVzbvBfKNpUjcftC2cXtN0OvGGT6MXGJg8UVQ1QQw1zmauYN6xpAUekGeQWM5uwW2CPGIozFrDk6soyWRExVQzL9z4km960s/yA0qA1x0Lm4uWrsgqdQz1Aqo
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: default
    type: Opaque
