---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: default
spec:
  encryptedData:
    accesskey: AgBspz0WWj/DY9aOqDE8ltS/8umO1qAUZRRm6i/h3UyVT+0/FuewG/x8Qi7gNz/W1dhe0PCEdz7Ie1QmcQs7J0qW95p0CJWtUNucBeDcvxo1ZbASl0Np43+bjd4F6kzPQPiQMh3dq+c66OEk8eqrqMeWJAvzyJo4GPZ1qMvySKGMDCd35nN/cEaAsTNqUasDXBDS9dvHMysWHzk+4VEcMbqTdK8ePOtZTVRgB8wbqrgu98piaGiL0pe87KOXT2VvV76zIzsygisjre+YAwMjHTrxX7IO6Nzym23hmIgwt5QlUhP7ZC6Lz87LBMHgMJW347DW8UsFRCO06d4luDaUjPBKxTqp+K2Qy/7lAEGXCRXGLVqVnpFWOfLb3T6cWpcs4TT/68Is1mdR0GA+kcWFQkzL+fTCfQnZKcvTP7up1fYRGaYE6UrxUZG3Mbbc+tV3wpbw0LY9mTcLVeSRK27nkZfTm9sLALzfQyi46rg7Pl84rHjNLwUTTzttavwOtzERaaq2mqhqDW96x5MOiCV4Xv0JwOe0wTu880O+p94NAh++SGY9LBBliNh8UPuw+NCL3eA5e0K9Yulfgx8jHD9lG4N/qcHWQCfympEZQlAvKJ9yA4fwlpN5w6dETSCwJUvHpa4Ur/2HKaQnYwZfPmEA3WHSC7Ki7uyLRq3Z1xkt82s8a7GuqfwlngksnfLvDL5BDqdeo6kaKHPsKPKN
    secretkey: AgCT/4W+yVtaLlmk76VHn6hSZtim8dCDmzuwTTic7sXxQYlChSaydbSIKV6yUrbkeFHUFFaNFAkCnJOf7UIJr75olEj8GGnf4LP/BY7vEwUiUkjf+w0x2HE9Sak3z7PZLP9cjcQyvOGAGDhM1iVYL6fTO73hUpqQl2pv13zEjQOvvcYs5sIvvwmONedU7/b5E5A8uuyd4uPYS81LhFVUrkT8ctWG82S6n/qgKjA9bjFCRm/m8wh12foFSUwkls3SxZy54eu6oaMm+uPb6HiRsOp4IHALoWqSwutGF8NYkBweM4/ZyCkCDwx61pRmQvDHf7joE/vOFfmSrVTsPTKyOdCynikrCaNcL6Bx/Jx8tckGZynDPalYXC8iGYkdka+ATr5WRmvWH9E/8m20CsjQL77DRbWuwK6XbsZKM7y6L+oC5cAPMwaXqfT/DMGB0Db/qdjxyQyqTbH6rk3YE8lir4uzCztc6KgzSb/dxECsE+e/Hsw+zfdIx5vm6rtrjRgXUhiBZk8MEnmV4UbTG1EVxSSQJHiFRFEqueSWQId365FB7AsfPxV9izbt2EwrN0lJSpq1pcxOV5oD4bbYj21NgfieweJsVrqbTAxbvNsk3V0/8XEtDwhjOVih8hpgAI1EutsEAZloPFQvAqQG8saJcuYfXb6Hy0t6Az9sO1XqyEbJ9OzEXQu5+eO7ci+dh+2kEJJq3Q06ksCRWjTs
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: default
